Repository brazilian-utils/brutils-python, pull requests merged in 2023-09, with the labels that each got.

#150 Feature: Validação de telefone
  README.md
  README_EN.md
  brutils/__init__.py
  brutils/phone.py
  tests/test_phone.py
Labels: feature

#154 Refactor: utilizando RegEX no arquivo `phone.py`
  README.md
  brutils/phone.py
  tests/test_phone.py
Labels: refactor

#160 Adicionar instrucoes de como criar o primeiro PR
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
Labels: documentation

#164 Adicionando Codigo de Conduta
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_EN.md
Labels: documentation

#167 Arrumando links dos badges de downloads dos READMEs
  README.md
  README_EN.md
Labels: documentation
