Repository brazilian-utils/brutils-python, pull requests merged in 2024-08, with the labels that each got.

#376 Criando métodos de busca de CEP/endereço consumindo a API da ViaCEP
  CHANGELOG.md
  README.md
  README_EN.md
  brutils/cep.py
  brutils/data/enums/__init__.py
  brutils/data/enums/better_enum.py
  brutils/data/enums/uf.py
  brutils/exceptions/__init__.py
  brutils/exceptions/cep.py
  brutils/types/__init__.py
  brutils/types/address.py
  pyproject.toml
  tests/test_cep.py
Labels: feature, python

#378 Pequenos ajustes nas novas features+ docs
  README.md
  README_EN.md
  brutils/__init__.py
  brutils/cep.py
  tests/test_cep.py
Labels: refactor

#382 Adicionando botão GitHub Sponsors - Cumbuca Dev
  .github/FUNDING.yml
Labels: documentation
